### PR TITLE
Dockerfile added

### PR DESCRIPTION
**Pull request by rysiekpl**
This pull request adds a `Dockerfile`, making it possible to easily build and run the `client` binary in a dockerized environment.

### CODE REVIEW

**Comment by rysiekpl** [comment]
Deployed in production using `docker`, seems to work fine.

**Comment by ghazel** [comment]
I'm not sure about `EXPOSE 8006/tcp`. NewNode listens on `localhost:8006`, and specifically does not offer the proxy to external interfaces. Does Docker handle the address translation in that case?

In addition, there is an ephemeral UDP (currently not easily settable from the command line). Does Docker need to open that port as well, so that inbound UDP response traffic arrives?

**Comment by rysiekpl** [comment]
> I'm not sure about `EXPOSE 8006/tcp`. NewNode listens on localhost:8006, and specifically does not offer the proxy to external interfaces. Does Docker handle the address translation in that case?

`EXPOSE` only exposes the port to the outside of the container, so that processes running outside of that container can still access whatever is running on that port within the container. Specifically, it does *not* expose the port to the external network on the host.

So question is, is the port `8006/tcp` something any external process could potentially need access to? I assumed so. But removing this line is also an option.

> In addition, there is an ephemeral UDP (currently not easily settable from the command line). Does Docker need to open that port as well, so that inbound UDP response traffic arrives?

Think of a docker container as a VM behind a firewall. If you were running this software on a VM, would the VM's firewall rules need to be adjusted to make it work?

**Comment by ghazel** [comment]
> > I'm not sure about `EXPOSE 8006/tcp`. NewNode listens on localhost:8006, and specifically does not offer the proxy to external interfaces. Does Docker handle the address translation in that case?
> 
> `EXPOSE` only exposes the port to the outside of the container, so that processes running outside of that container can still access whatever is running on that port within the container. Specifically, it does _not_ expose the port to the external network on the host.
> 
> So question is, is the port `8006/tcp` something any external process could potentially need access to? I assumed so. But removing this line is also an option.

External processes should be able to access it. How do they address it? With localhost, or with some IP allocated to the Docker VM?

> > In addition, there is an ephemeral UDP (currently not easily settable from the command line). Does Docker need to open that port as well, so that inbound UDP response traffic arrives?
> 
> Think of a docker container as a VM behind a firewall. If you were running this software on a VM, would the VM's firewall rules need to be adjusted to make it work?

That depends on how the VM is networked to the host. Is there a mortuary network adapter with an IP?

**Pull request merged**
