### PR TITLE
Simple integration test

### PR DESCRIPTION
**Pull request by inetic**

### CODE REVIEW

**Comment by inetic** [comment]
Please don't merge yet, I fixed a few issues but there still seem to be a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug). I.e. it currently passes the CI tests only when I have logging enabled, need to figure out what that is prior to merging.

**Comment by shalunov** [comment]
Travis doesn't trigger on commits in your forked repo, does it? Gotta send a pull request to see if CI passes?

**Comment by inetic** [comment]
By default it doesn't. One could enable it though just like you enabled it for your repo. Unfortunately it did not work for me out of the box because the submodules aren't public.

**Comment by inetic** [comment]
@shalunov, it's good to go now.

**Comment by inetic** [comment]
resolves #15

**Comment by shalunov** [comment]
https://travis-ci.org/clostra/dcdn/builds/234789753 passed

https://travis-ci.org/clostra/dcdn/builds/234905800 failed

Same code?

**Pull request merged**
