### PR TITLE
Add clang-tidy to build.sh (resolves #37)

### LINKED ISSUE #37: add clang-tidy to Travis build
- [x] try clang-tidy
- [x] check if it even works on C
- [x] post the output in this issue
- [x] figure out the relationship with #35
- [x] decide if it's worth it to add it to the build
- [x] add to Travis build

### PR DESCRIPTION
**Pull request by inetic**

### CODE REVIEW

**Comment by shalunov** [comment]
This is WIP, right?

**Comment by inetic** [comment]
Yes

**Comment by inetic** [comment]
Still trying to make clang-tidy to work together with sanitizers. So far the only positive byproduct is that i managed to increase the clang version on mac.

**Comment by inetic** [comment]
OK, `clang-tidy` now works on both macos and linux. A nice byproduct is that I (had to) upgraded clang versions on both systems.

Note: `clang-tidy` only prints out warnings which are not treated as errors. This can be changed with the `-warnings-as-errors` but we should first have a consensus which warnings to treat as such.

**Comment by inetic** [comment]
Resolves #37

**Pull request merged**
